# Set up and run this Streamlit App
import streamlit as st
import helper_functions.llm # <--- This is the helper function that we have created 🆕
from logics import customer_query_handler
import pandas as pd
import json
from helper_functions.utility import check_password

# region <--------- Streamlit App Configuration --------->
st.set_page_config(
    # layout="centered",
    page_title="My Streamlit App"
)
# endregion <--------- Streamlit App Configuration --------->

# Do not continue if check_password is not True.  
if not check_password():  
    st.stop()

st.title("Streamlit App")

form = st.form(key="form")
form.subheader("Prompt")

user_prompt = form.text_area("Enter your prompt here", height=200)

if form.form_submit_button("Submit"):
    st.toast(f"User Input Submitted - {user_prompt}")
    # response = llm.get_completion(user_prompt) # <--- This calls the helper function that we have created 🆕
    response, dict_details = customer_query_handler.process_user_message(user_prompt) 
    st.write(response) # <--- This displays the response generated by the LLM onto the frontend 🆕
    st.divider()
    st.write(pd.DataFrame.from_dict(dict_details))
    
    #print(f"User Input is {user_prompt}")
